on:
  push:
    branches:
    - main
    - release/*
  schedule:
  - cron: "0 2 * * 1-5"
jobs:
  test:
    name: testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@main
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
